import { randomUUID } from "node:crypto";

import type { FastifyInstance } from "fastify";

import { config } from "../config.js";
import { authorizeOrderAccess } from "./commerce.js";
import { asObject, audit, HttpError, pagination } from "../platform.js";
import { createNationalShipment, fetchTracking, quoteNational } from "../providers/skydropx.js";
import type { AppContext } from "../types.js";

function workOrder(row: any): any {
  return {
    ...row,
    checklist: {
      dtf_sent_to_print: Boolean(row.dtf_sent_to_print_at), dtf_printed: Boolean(row.dtf_printed_at),
      dtf_applied: Boolean(row.dtf_applied_at), packed: Boolean(row.packed_at), shipped: Boolean(row.shipped_at), delivered: Boolean(row.delivered_at),
      dtf_sent_to_print_at: row.dtf_sent_to_print_at, dtf_printed_at: row.dtf_printed_at,
      dtf_applied_at: row.dtf_applied_at, packed_at: row.packed_at, shipped_at: row.shipped_at, delivered_at: row.delivered_at
    }
  };
}

async function fullOrder(context: AppContext, id: string): Promise<any> {
  const order=(await context.database.query("select * from orders where id=$1",[id])).rows[0];if(!order)throw new HttpError(404,"Pedido no encontrado");const items=(await context.database.query("select * from order_items where order_id=$1 order by created_at",[id])).rows;const responseOrder={...order};delete responseOrder.customer_access_token_hash;return{...responseOrder,email:order.customer_email,phone:order.customer_phone,drop_label:order.drop_number?`#${order.drop_number}`:null,items};
}

async function inventoryEntry(context: AppContext, body: Record<string,any>, actor?: string): Promise<any> {
  const values=[body.garment_type,body.garment_model??"",body.color,body.size,Number(body.grammage_g),body.fit??""];
  const client=await context.database.connect();try{await client.query("begin");let item=(await client.query<any>("select * from inventory_items where garment_type=$1 and garment_model=$2 and color=$3 and size=$4 and grammage_g=$5 and fit=$6 for update",values)).rows[0];if(!item){item=(await client.query<any>(`insert into inventory_items(id,garment_type,garment_model,color,size,grammage_g,fit,quantity,supplier_cost_mxn)
    values($1,$2,$3,$4,$5,$6,$7,0,$8) returning *`,[randomUUID(),...values,body.supplier_cost_mxn??0])).rows[0];}await client.query("update inventory_items set quantity=quantity+$2,supplier_cost_mxn=coalesce($3,supplier_cost_mxn),updated_at=now() where id=$1",[item.id,Number(body.quantity),body.supplier_cost_mxn??null]);await client.query("insert into stock_entries(id,inventory_item_id,quantity,supplier_name,unit_cost_mxn,source_ref) values($1,$2,$3,$4,$5,$6)",[randomUUID(),item.id,Number(body.quantity),body.supplier_name??null,body.supplier_cost_mxn??null,body.source_ref??null]);await client.query("insert into inventory_movements(id,inventory_item_id,movement_type,quantity,reason,actor,source_ref) values($1,$2,'entry',$3,$4,$5,$6)",[randomUUID(),item.id,Number(body.quantity),body.reason??"Entrada de inventario",actor??null,body.source_ref??null]);await client.query("commit");return(await context.database.query("select * from inventory_items where id=$1",[item.id])).rows[0];}catch(error){await client.query("rollback");throw error;}finally{client.release();}
}

async function setOrderStatus(context:AppContext,request:any,id:string,status:string,reason?:string):Promise<any>{const client=await context.database.connect();try{await client.query("begin");const order=(await client.query("select * from orders where id=$1 for update",[id])).rows[0];if(!order)throw new HttpError(404,"Pedido no encontrado");await client.query("update orders set status=$2,updated_at=now() where id=$1",[id,status]);await client.query("insert into order_state_history(id,order_id,previous_status,new_status,source,reason,changed_by) values($1,$2,$3,$4,'admin',$5,$6)",[randomUUID(),id,order.status,status,reason??null,request.actor?.accountId??null]);await client.query("commit");await audit(request,"order.status_updated","order",id,{previous_status:order.status,status,reason});return{order_id:id,previous_status:order.status,status};}catch(error){await client.query("rollback");throw error;}finally{client.release();}}

async function shipmentForOrder(context:AppContext,orderId:string):Promise<any>{return(await context.database.query("select * from shipments where order_id=$1",[orderId])).rows[0]??null;}

export async function registerOperations(app:FastifyInstance,context:AppContext):Promise<void>{
  app.get("/inventory/items",async(request)=>{const q=asObject(request.query);const values:any[]=[];const where:string[]=[];for(const key of ["garment_type","garment_model","color","size","grammage_g","fit"])if(q[key]!==undefined&&q[key]!==""){values.push(q[key]);where.push(`${key}=$${values.length}`);}return(await context.database.query(`select * from inventory_items ${where.length?`where ${where.join(" and ")}`:""} order by garment_type,color,size`,values)).rows;});
  app.get("/inventory/stock",async(request)=>{const q=asObject(request.query);const keys=["garment_type","garment_model","color","size","grammage_g","fit"];const values=keys.map(k=>q[k]??(k==="garment_model"||k==="fit"?"":undefined));const result=await context.database.query("select coalesce(sum(quantity),0)::integer quantity from inventory_items where garment_type=$1 and garment_model=$2 and color=$3 and size=$4 and grammage_g=$5 and fit=$6",values);return{quantity:Number(result.rows[0]?.quantity??0)};});
  app.get<{Params:{id:string}}>("/inventory/items/:id/movements",async(request)=>(await context.database.query("select * from inventory_movements where inventory_item_id=$1 order by created_at desc",[request.params.id])).rows);
  app.get("/admin/inventory/items",async(request)=>{const q=asObject(request.query);const{limit,offset}=pagination(q);const values:any[]=[];const where:string[]=[];if(q.garment_type){values.push(q.garment_type);where.push(`garment_type=$${values.length}`);}if(q.in_stock_only==="true")where.push("quantity>0");values.push(limit,offset);const total=Number((await context.database.query(`select count(*) from inventory_items ${where.length?`where ${where.join(" and ")}`:""}`,values.slice(0,-2))).rows[0]?.count??0);const items=(await context.database.query(`select * from inventory_items ${where.length?`where ${where.join(" and ")}`:""} order by created_at desc limit $${values.length-1} offset $${values.length}`,values)).rows;return{items,total,limit,offset};});
  app.get("/admin/inventory/movements",async(request)=>{const q=asObject(request.query);const{limit,offset}=pagination(q);const values:any[]=[];const where:string[]=[];for(const key of ["movement_type","inventory_item_id"])if(q[key]){values.push(q[key]);where.push(`${key}=$${values.length}`);}values.push(limit,offset);const total=Number((await context.database.query(`select count(*) from inventory_movements ${where.length?`where ${where.join(" and ")}`:""}`,values.slice(0,-2))).rows[0]?.count??0);const items=(await context.database.query(`select * from inventory_movements ${where.length?`where ${where.join(" and ")}`:""} order by created_at desc limit $${values.length-1} offset $${values.length}`,values)).rows;return{items,total,limit,offset};});
  app.post("/admin/inventory/entries",async(request,reply)=>{const row=await inventoryEntry(context,asObject(request.body),request.actor?.accountId);await audit(request,"inventory.entry","inventory_item",row.id,request.body);reply.status(201);return row;});
  app.post("/admin/inventory/entries/batch",async(request,reply)=>{const items=asObject(request.body).items;if(!Array.isArray(items))throw new HttpError(400,"items requerido");const results=[];for(const item of items)results.push(await inventoryEntry(context,asObject(item),request.actor?.accountId));await audit(request,"inventory.batch_entry","inventory","batch",{count:results.length});reply.status(201);return{items:results};});
  app.post("/admin/inventory/adjustments",async(request)=>{const body=asObject(request.body);const client=await context.database.connect();try{await client.query("begin");const item=(await client.query("select * from inventory_items where id=$1 for update",[body.inventory_item_id])).rows[0];if(!item)throw new HttpError(404,"Inventario no encontrado");const delta=Number(body.new_quantity)-Number(item.quantity);const row=(await client.query("update inventory_items set quantity=$2,updated_at=now() where id=$1 returning *",[item.id,body.new_quantity])).rows[0];await client.query("insert into inventory_movements(id,inventory_item_id,movement_type,quantity,reason,actor,source_ref) values($1,$2,'adjustment',$3,$4,$5,$6)",[randomUUID(),item.id,delta,body.reason??"Ajuste manual",request.actor?.accountId??null,body.source_ref??null]);await client.query("commit");await audit(request,"inventory.adjustment","inventory_item",item.id,body);return row;}catch(error){await client.query("rollback");throw error;}finally{client.release();}});
  const internalMovement=async(request:any,type:string)=>{const body=asObject(request.body);const itemId=body.inventory_item_id;const quantity=Number(body.quantity??0)*(type==="release"?1:-1);const row=(await context.database.query("update inventory_items set quantity=quantity+$2,updated_at=now() where id=$1 and quantity+$2>=0 returning *",[itemId,quantity])).rows[0];if(!row)throw new HttpError(409,"Stock insuficiente o SKU inexistente");await context.database.query("insert into inventory_movements(id,inventory_item_id,movement_type,quantity,reason,source_ref) values($1,$2,$3,$4,$5,$6)",[randomUUID(),itemId,type,quantity,body.reason??null,body.source_ref??null]);return row;};
  app.post("/internal/inventory/consume/payment-confirmed",async request=>internalMovement(request,"payment_confirmed"));app.post("/internal/inventory/release/payment-failed",async request=>internalMovement(request,"release"));app.post("/internal/inventory/consume/merma",async request=>internalMovement(request,"merma"));

  app.get("/admin/orders",async(request)=>{const q=asObject(request.query);const{limit,offset}=pagination(q);const values:any[]=[];const where:string[]=[];for(const key of ["status","shipping_method"])if(q[key]){values.push(q[key]);where.push(`o.${key}=$${values.length}`);}if(q.q){values.push(`%${q.q}%`);where.push(`(o.customer_email ilike $${values.length} or o.id::text ilike $${values.length})`);}values.push(limit,offset);const total=Number((await context.database.query(`select count(*) from orders o ${where.length?`where ${where.join(" and ")}`:""}`,values.slice(0,-2))).rows[0]?.count??0);const rows=(await context.database.query(`select o.* from orders o ${where.length?`where ${where.join(" and ")}`:""} order by o.created_at desc limit $${values.length-1} offset $${values.length}`,values)).rows;const items=[];for(const row of rows)items.push(await fullOrder(context,row.id));return{items,total,limit,offset};});
  app.get<{Params:{order_id:string}}>("/admin/orders/:order_id",async(request)=>{const order=await fullOrder(context,request.params.order_id);const work_orders=(await context.database.query("select * from work_orders where order_id=$1 order by created_at",[request.params.order_id])).rows.map(workOrder);return{order,work_orders};});
  app.get<{Params:{order_id:string}}>("/admin/orders/:order_id/work-orders",async(request)=>(await context.database.query("select * from work_orders where order_id=$1 order by created_at",[request.params.order_id])).rows.map(workOrder));
  app.patch<{Params:{order_id:string}}>("/ops/orders/:order_id/status",async(request)=>{const body=asObject(request.body);return setOrderStatus(context,request,request.params.order_id,String(body.status),body.reason);});
  app.patch<{Params:{work_order_id:string}}>("/admin/work-orders/:work_order_id/checklist",async(request)=>{const body=asObject(request.body);const row=(await context.database.query("select * from work_orders where id=$1",[request.params.work_order_id])).rows[0];if(!row)throw new HttpError(404,"Orden de trabajo no encontrada");const map:Record<string,string>={dtf_sent_to_print:"dtf_sent_to_print_at",dtf_printed:"dtf_printed_at",dtf_applied:"dtf_applied_at",packed:"packed_at",shipped:"shipped_at",delivered:"delivered_at"};const sets:string[]=[];const values:any[]=[row.id];for(const[key,column]of Object.entries(map))if(body[key]!==undefined)sets.push(`${column}=${body[key]?"now()":"null"}`);if(sets.length===0)throw new HttpError(400,"Checklist vacío");let status=row.status;if(body.delivered)status="delivered";else if(body.shipped)status="shipped";else if(body.packed)status="packed";else if(body.dtf_applied)status="produced";else if(body.dtf_sent_to_print||body.dtf_printed)status="in_production";const updated=(await context.database.query(`update work_orders set ${sets.join(",")},status=$2,updated_at=now() where id=$1 returning *`,[...values,status])).rows[0];if(body.shipped||body.delivered)await setOrderStatus(context,request,row.order_id,body.delivered?"delivered":"shipped",body.reason);await audit(request,"work_order.checklist_updated","work_order",row.id,body);return{work_order:workOrder(updated),order_status:(await context.database.query("select status from orders where id=$1",[row.order_id])).rows[0]?.status};});
  app.post<{Params:{work_order_id:string}}>("/admin/work-orders/:work_order_id/merma",async(request)=>{const body=asObject(request.body);const work=(await context.database.query("select w.*,oi.garment_type,oi.garment_model,oi.color,oi.size,oi.grammage_g,oi.fit from work_orders w join order_items oi on oi.id=w.order_item_id where w.id=$1",[request.params.work_order_id])).rows[0];if(!work)throw new HttpError(404,"Orden de trabajo no encontrada");const inv=(await context.database.query("select * from inventory_items where garment_type=$1 and garment_model=$2 and color=$3 and size=$4 and grammage_g=$5 and fit=$6",[work.garment_type,work.garment_model,work.color,work.size,work.grammage_g,work.fit])).rows[0];if(!inv||Number(inv.quantity)<Number(body.quantity))throw new HttpError(409,"Stock insuficiente para registrar merma");const reference=`merma:${work.id}:${randomUUID()}`;await context.database.query("update inventory_items set quantity=quantity-$2,updated_at=now() where id=$1",[inv.id,body.quantity]);await context.database.query("insert into inventory_movements(id,inventory_item_id,movement_type,quantity,reason,actor,source_ref) values($1,$2,'merma',$3,$4,$5,$6)",[randomUUID(),inv.id,-Number(body.quantity),body.reason_code,request.actor?.accountId??null,reference]);await context.database.query("insert into work_order_failures(id,work_order_id,order_id,order_item_id,reason_code,notes,quantity,merma_reference,recorded_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9)",[randomUUID(),work.id,work.order_id,work.order_item_id,body.reason_code,body.notes??null,body.quantity,reference,request.actor?.accountId??null]);const updated=(await context.database.query("update work_orders set failures_count=failures_count+1,last_failure_at=now(),updated_at=now() where id=$1 returning *",[work.id])).rows[0];await audit(request,"work_order.merma_recorded","work_order",work.id,body);return{work_order:workOrder(updated)};});
  app.get<{Params:{order_id:string}}>("/internal/orders/:order_id/tracking",async(request)=>{const order=await fullOrder(context,request.params.order_id);return{order_id:order.id,status:order.status,tracking_number:order.tracking_number,tracking_carrier:order.tracking_carrier,tracking_url:order.tracking_url};});
  app.get<{Params:{order_id:string}}>("/internal/orders/:order_id/address/local",async(request)=>{const order=await fullOrder(context,request.params.order_id);return{order_id:order.id,address:order.address,email:order.email,phone:order.phone};});
  app.post<{Params:{drop_id:string}}>("/internal/drops/:drop_id/counter",async(request)=>(await context.database.query("insert into drop_counters(drop_id,last_number)values($1,1)on conflict(drop_id)do update set last_number=drop_counters.last_number+1,updated_at=now()returning *",[request.params.drop_id])).rows[0]);

  const skuQuote=async(q:Record<string,any>)=>{const keys=["garment_type","garment_model","color","size","grammage_g","fit"];const row=(await context.database.query("select * from sku_pricing_rules where garment_type=$1 and garment_model=$2 and color=$3 and size=$4 and grammage_g=$5 and fit=$6 and is_active=true",keys.map(k=>q[k]??(k==="garment_model"||k==="fit"?"":undefined)))).rows[0];if(!row)throw new HttpError(404,"Regla de precio no encontrada");return row;};
  app.get("/pricing/sku",async request=>skuQuote(asObject(request.query)));app.get("/internal/pricing/sku",async request=>skuQuote(asObject(request.query)));
  app.get("/admin/pricing/sku-rules",async(request)=>{const q=asObject(request.query);const{limit,offset}=pagination(q);const items=(await context.database.query("select * from sku_pricing_rules order by created_at desc limit $1 offset $2",[limit,offset])).rows;const total=Number((await context.database.query("select count(*) from sku_pricing_rules")).rows[0]?.count??0);return{items,total,limit,offset};});
  app.post("/admin/pricing/sku-rules",async(request,reply)=>{const b=asObject(request.body);const row=(await context.database.query(`insert into sku_pricing_rules(id,garment_type,garment_model,color,size,grammage_g,fit,sale_price_mxn,provider_price_mxn,dtf_cost_mxn,packaging_cost_mxn,is_active)
    values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)returning *`,[randomUUID(),b.garment_type,b.garment_model??"",b.color,b.size,b.grammage_g,b.fit??"",b.sale_price_mxn,b.provider_price_mxn??0,b.dtf_cost_mxn??0,b.packaging_cost_mxn??0,b.is_active??true])).rows[0];reply.status(201);return row;});
  app.post("/admin/pricing/sku-rules/upsert",async request=>{const b=asObject(request.body);return(await context.database.query(`insert into sku_pricing_rules(id,garment_type,garment_model,color,size,grammage_g,fit,sale_price_mxn,provider_price_mxn,dtf_cost_mxn,packaging_cost_mxn,is_active)
    values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)on conflict(garment_type,garment_model,color,size,grammage_g,fit)do update set sale_price_mxn=excluded.sale_price_mxn,provider_price_mxn=excluded.provider_price_mxn,dtf_cost_mxn=excluded.dtf_cost_mxn,packaging_cost_mxn=excluded.packaging_cost_mxn,is_active=excluded.is_active,updated_at=now()returning *`,[randomUUID(),b.garment_type,b.garment_model??"",b.color,b.size,b.grammage_g,b.fit??"",b.sale_price_mxn,b.provider_price_mxn??0,b.dtf_cost_mxn??0,b.packaging_cost_mxn??0,b.is_active??true])).rows[0];});
  app.patch<{Params:{id:string}}>("/admin/pricing/sku-rules/:id",async(request)=>{const b=asObject(request.body);const allowed=["sale_price_mxn","provider_price_mxn","dtf_cost_mxn","packaging_cost_mxn","is_active"];const keys=allowed.filter(k=>b[k]!==undefined);if(!keys.length)throw new HttpError(400,"Payload vacío");const values=keys.map(k=>b[k]);values.push(request.params.id);const row=(await context.database.query(`update sku_pricing_rules set ${keys.map((k,i)=>`${k}=$${i+1}`).join(",")},updated_at=now() where id=$${values.length} returning *`,values)).rows[0];if(!row)throw new HttpError(404,"Regla no encontrada");return row;});
  app.get("/admin/pricing/customizer-config",async()=>(await context.database.query("select * from customizer_pricing_configs where is_active=true order by created_at desc limit 1")).rows[0]);
  app.put("/admin/pricing/customizer-config",async(request)=>{const b=asObject(request.body);await context.database.query("update customizer_pricing_configs set is_active=false where is_active=true");return(await context.database.query("insert into customizer_pricing_configs(id,base_price_mxn,per_image_price_mxn,included_images,max_images,quality_upgrade_price_mxn,is_active)values($1,$2,$3,$4,$5,$6,true)returning *",[randomUUID(),b.base_price_mxn,b.per_image_price_mxn,b.included_images??0,b.max_images??10,b.quality_upgrade_price_mxn??0])).rows[0];});
  const quoteOrder=async(body:Record<string,any>)=>{const items=Array.isArray(body.items)?body.items:[];let total=0;const lines=[];for(const item of items){const price=Number(item.unit_price_mxn??item.sale_price_mxn??0)*Number(item.quantity??1);total+=price;lines.push({...item,line_total_mxn:price});}return{currency:"MXN",subtotal_mxn:total,total_mxn:total,items:lines};};app.post("/admin/pricing/quote-order",async request=>quoteOrder(asObject(request.body)));app.post("/internal/pricing/quote-order",async request=>quoteOrder(asObject(request.body)));

  app.post<{Params:{order_id:string}}>("/admin/shipping/national/orders/:order_id/shipment",async(request)=>{const order=await fullOrder(context,request.params.order_id);if(order.shipping_method!=="national")throw new HttpError(409,"El pedido no usa envío nacional");let shipment=await shipmentForOrder(context,order.id);if(!shipment){const checkout=(await context.database.query("select shipping_quote_id from checkout_sessions where id=$1",[order.checkout_session_id])).rows[0];const created=await createNationalShipment(order,String(checkout?.shipping_quote_id??"national-standard"),asObject(request.body));const id=randomUUID();shipment=(await context.database.query(`insert into shipments(id,order_id,shipping_method,status,provider,provider_shipment_id,tracking_number,tracking_carrier,tracking_url,label_url,shipped_at)
      values($1,$2,'national','shipped','skydropx',$3,$4,$5,$6,$7,now())returning *`,[id,order.id,created.provider_shipment_id,created.tracking_number,created.tracking_carrier,created.tracking_url,created.label_url])).rows[0];await context.database.query("insert into shipment_events(id,shipment_id,event_type,payload)values($1,$2,'created',$3)",[randomUUID(),id,created.raw]);}await context.database.query("update orders set status='shipped',tracking_number=$2,tracking_carrier=$3,tracking_url=$4,shipping_label_url=$5,updated_at=now() where id=$1",[order.id,shipment.tracking_number,shipment.tracking_carrier,shipment.tracking_url,shipment.label_url]);await audit(request,"shipping.national_created","order",order.id,request.body);return{shipment,order_status:"shipped"};});
  app.post<{Params:{order_id:string}}>("/admin/shipping/national/orders/:order_id/tracking/refresh",async(request)=>{let shipment=await shipmentForOrder(context,request.params.order_id);if(!shipment)throw new HttpError(404,"Envío no encontrado");const tracking=await fetchTracking(shipment.tracking_number,shipment.tracking_carrier??"Skydropx");for(const event of tracking.events)await context.database.query("insert into shipment_events(id,shipment_id,event_type,payload)values($1,$2,'tracking',$3)",[randomUUID(),shipment.id,event]);if(tracking.delivered){shipment=(await context.database.query("update shipments set status='delivered',delivered_at=now(),updated_at=now()where id=$1 returning *",[shipment.id])).rows[0];await context.database.query("update orders set status='delivered',updated_at=now()where id=$1",[request.params.order_id]);}await context.database.query("insert into shipment_events(id,shipment_id,event_type,payload)values($1,$2,'tracking_refreshed',$3)",[randomUUID(),shipment.id,tracking.raw]);const events=Number((await context.database.query("select count(*) from shipment_events where shipment_id=$1",[shipment.id])).rows[0]?.count??0);return{shipment,delivered:tracking.delivered,events_count:events,order_status:(await context.database.query("select status from orders where id=$1",[request.params.order_id])).rows[0]?.status};});
  const localAction=async(request:any,status:string)=>{const order=await fullOrder(context,request.params.order_id);if(order.shipping_method!=="local")throw new HttpError(409,"El pedido no usa envío local");let shipment=await shipmentForOrder(context,order.id);const now=new Date();if(!shipment){shipment=(await context.database.query("insert into shipments(id,order_id,shipping_method,status,provider,local_route_date,local_ready_at)values($1,$2,'local',$3,'saut-local',$4,$5)returning *",[randomUUID(),order.id,status,asObject(request.body).route_date??now.toISOString().slice(0,10),status==="ready"?now:null])).rows[0];}else{const column=status==="out_for_delivery"?"out_for_delivery_at":status==="delivered"?"delivered_at":status==="failed"?"failed_at":"local_ready_at";shipment=(await context.database.query(`update shipments set status=$2,${column}=now(),failed_attempts=failed_attempts+$3,updated_at=now()where id=$1 returning *`,[shipment.id,status,status==="failed"?1:0])).rows[0];}if(status==="delivered"||status==="failed"){const body=asObject(request.body);if(body.photo_url||body.notes)await context.database.query("insert into local_delivery_evidences(id,shipment_id,photo_url,notes,created_by)values($1,$2,$3,$4,$5)",[randomUUID(),shipment.id,body.photo_url??null,body.notes??null,request.actor?.accountId??null]);}const orderStatus=status==="ready"?"ready_for_delivery":status;await setOrderStatus(context,request,order.id,orderStatus);await context.database.query("insert into shipment_events(id,shipment_id,event_type,payload)values($1,$2,$3,$4)",[randomUUID(),shipment.id,status,request.body??{}]);return{shipment,order_status:orderStatus};};
  app.post("/admin/shipping/local/orders/:order_id/ready",async request=>localAction(request,"ready"));app.post("/admin/shipping/local/orders/:order_id/out-for-delivery",async request=>localAction(request,"out_for_delivery"));app.post("/admin/shipping/local/orders/:order_id/delivered",async request=>localAction(request,"delivered"));app.post("/admin/shipping/local/orders/:order_id/failed",async request=>localAction(request,"failed"));
  const changeAddress=async(request:any)=>{const body=asObject(request.body);const orderRecord=(await context.database.query("select * from orders where id=$1",[request.params.order_id])).rows[0];if(!orderRecord)throw new HttpError(404,"Pedido no encontrado");if(!request.url.startsWith("/admin/"))await authorizeOrderAccess(context,request,orderRecord);const order=await fullOrder(context,request.params.order_id);if(order.shipping_method!=="local")throw new HttpError(409,"Solo se puede cambiar dirección local");const shipment=await shipmentForOrder(context,order.id);await context.database.query("insert into local_address_changes(id,shipment_id,order_id,old_address,new_address,reason,changed_by)values($1,$2,$3,$4,$5,$6,$7)",[randomUUID(),shipment?.id??null,order.id,order.address,body.address,body.reason??null,request.actor?.accountId??null]);await context.database.query("update orders set address=$2,updated_at=now() where id=$1",[order.id,body.address]);return{order_id:order.id,address:body.address,shipment};};app.patch("/admin/shipping/local/orders/:order_id/address",changeAddress);app.patch("/shipping/local/orders/:order_id/address",changeAddress);
  app.get("/admin/shipping/local/routes/today",async(request)=>{const date=String(asObject(request.query).date??new Date().toISOString().slice(0,10));const rows=(await context.database.query("select s.id shipment_id,s.order_id,s.status,o.customer_email email,o.customer_phone phone,o.address from shipments s join orders o on o.id=s.order_id where s.shipping_method='local' and s.local_route_date=$1 order by s.created_at",[date])).rows;const stops=rows.map(row=>({...row,notes:null}));return{date,total:stops.length,stops,printable_text:stops.map((s,i)=>`${i+1}. ${s.address?.line1??""} — ${s.email}`).join("\n")};});
  app.get("/admin/shipping/shipments",async(request)=>{const q=asObject(request.query);const{limit,offset}=pagination(q);const values:any[]=[];const where:string[]=[];for(const key of ["shipping_method","status","order_id"])if(q[key]){values.push(q[key]);where.push(`s.${key}=$${values.length}`);}values.push(limit,offset);const total=Number((await context.database.query(`select count(*) from shipments s ${where.length?`where ${where.join(" and ")}`:""}`,values.slice(0,-2))).rows[0]?.count??0);const shipments=(await context.database.query(`select s.* from shipments s ${where.length?`where ${where.join(" and ")}`:""} order by s.created_at desc limit $${values.length-1} offset $${values.length}`,values)).rows;const items=[];for(const shipment of shipments){const order=await fullOrder(context,shipment.order_id);const events=(await context.database.query("select id,event_type,payload,created_at from shipment_events where shipment_id=$1 order by created_at desc",[shipment.id])).rows;items.push({shipment,order:{id:order.id,email:order.email,phone:order.phone,status:order.status,shipping_method:order.shipping_method,address:order.address,tracking_number:order.tracking_number,tracking_carrier:order.tracking_carrier,tracking_url:order.tracking_url,created_at:order.created_at,updated_at:order.updated_at},events});}return{items,total,limit,offset};});
  app.post("/webhooks/shipping/skydropx",async(request)=>{const secret=request.headers["x-skydropx-webhook-secret"]??request.headers.authorization?.replace(/^Bearer /,"");if(secret!==config.SKYDROPX_WEBHOOK_SECRET)throw new HttpError(401,"Webhook auth inválida");const body=asObject(request.body);const shipment=(await context.database.query("select * from shipments where provider_shipment_id=$1 or tracking_number=$2 limit 1",[body.shipment_id??null,body.tracking_number??null])).rows[0];if(!shipment)return{received:true,matched:false};await context.database.query("update shipments set status=$2,updated_at=now() where id=$1",[shipment.id,body.status??shipment.status]);await context.database.query("insert into shipment_events(id,shipment_id,event_type,payload)values($1,$2,'skydropx_webhook',$3)",[randomUUID(),shipment.id,body]);return{received:true,matched:true};});
  app.post("/internal/shipping/quotes/national",async request=>({quotes:await quoteNational(asObject(asObject(request.body).address_to??asObject(request.body).address),asObject(request.body).order_id)}));
}
