import { randomUUID } from "node:crypto";

import type { FastifyInstance, FastifyRequest } from "fastify";

import { config } from "../config.js";
import { asObject, audit, bearerToken, HttpError, pagination, verifyAccessToken } from "../platform.js";
import type { AppContext } from "../types.js";

const reasons = [
  { code: "order_status", label: "Estado de mi pedido", requires_order: true },
  { code: "change_address", label: "Cambiar dirección", requires_order: true },
  { code: "refund", label: "Reembolso", requires_order: true },
  { code: "product", label: "Duda sobre un producto", requires_order: false },
  { code: "customizer", label: "Ayuda con personalización", requires_order: false },
  { code: "other", label: "Otro", requires_order: false }
];

async function optionalActor(request: FastifyRequest): Promise<any | null> {
  const token = bearerToken(request);
  if (!token) return null;
  try { return await verifyAccessToken(token); } catch { return null; }
}

async function caseDetail(context: AppContext, id: string): Promise<any> {
  const supportCase=(await context.pool.query("select * from support_cases where id=$1",[id])).rows[0];if(!supportCase)throw new HttpError(404,"Caso no encontrado");
  const messages=(await context.pool.query("select * from support_case_messages where case_id=$1 order by created_at",[id])).rows;
  const output=[];for(const message of messages){const attachments=(await context.pool.query("select id,asset_id,file_url,file_name,mime_type,size_bytes,created_at from support_case_attachments where message_id=$1 order by created_at",[message.id])).rows;output.push({...message,attachments});}
  return{case:supportCase,messages:output};
}

async function ensureCaseAccess(context:AppContext,request:FastifyRequest,supportCase:any):Promise<void>{if(request.url.startsWith("/admin/"))return;const actor=await optionalActor(request);if(actor&&supportCase.account_id===actor.accountId)return;const query=asObject(request.query);const email=String(query.guest_email??"").toLowerCase();const code=String(query.guest_order_code??"").replaceAll("-","").toUpperCase();if(email&&email===String(supportCase.guest_email??supportCase.contact_email).toLowerCase()&&code&&code===String(supportCase.guest_order_code??supportCase.linked_order_code??"").replaceAll("-","").toUpperCase())return;throw new HttpError(403,"No tienes acceso a este caso");}

async function addMessage(context:AppContext,caseId:string,body:Record<string,any>,sender:{type:string;accountId?:string;label?:string},internal=false):Promise<any>{const id=randomUUID();await context.pool.query("insert into support_case_messages(id,case_id,sender_type,sender_account_id,sender_label,message,is_internal)values($1,$2,$3,$4,$5,$6,$7)",[id,caseId,sender.type,sender.accountId??null,sender.label??null,body.message,internal]);for(const attachment of Array.isArray(body.attachments)?body.attachments:[])await context.pool.query("insert into support_case_attachments(id,case_id,message_id,asset_id,file_url,file_name,mime_type,size_bytes)values($1,$2,$3,$4,$5,$6,$7,$8)",[randomUUID(),caseId,id,attachment.asset_id??null,attachment.file_url,attachment.file_name??null,attachment.mime_type??null,attachment.size_bytes??null]);await context.pool.query("update support_cases set last_message_at=now(),updated_at=now() where id=$1",[caseId]);return caseDetail(context,caseId);}

async function deliverNotification(context:AppContext,id:string):Promise<any>{const delivery=(await context.pool.query("select * from notification_deliveries where id=$1",[id])).rows[0];if(!delivery)throw new HttpError(404,"Notificación no encontrada");if(config.NOTIFICATION_DEV_MODE){return(await context.pool.query("update notification_deliveries set status='delivered',attempts=attempts+1,provider_message_id=$2,delivered_at=now(),updated_at=now()where id=$1 returning *",[id,`dev-${randomUUID()}`])).rows[0];}if(!config.sendgridApiKey)throw new HttpError(503,"SENDGRID_API_KEY no configurado");const payload=delivery.payload??{};const response=await fetch("https://api.sendgrid.com/v3/mail/send",{method:"POST",headers:{authorization:`Bearer ${config.sendgridApiKey}`,"content-type":"application/json"},body:JSON.stringify({personalizations:[{to:[{email:delivery.recipient}],subject:payload.subject??"Notificación SAUT"}],from:{email:config.sendgridFromEmail},content:[{type:"text/plain",value:payload.message??payload.summary??"Notificación"}]})});if(!response.ok){const message=await response.text();await context.pool.query("update notification_deliveries set status='failed',attempts=attempts+1,last_error=$2,updated_at=now()where id=$1",[id,message]);throw new HttpError(503,"SendGrid rechazó la notificación");}return(await context.pool.query("update notification_deliveries set status='delivered',attempts=attempts+1,provider_message_id=$2,delivered_at=now(),updated_at=now()where id=$1 returning *",[id,`sg-${randomUUID()}`])).rows[0];}

async function queueNotification(context:AppContext,template:string,recipient:string,payload:Record<string,any>,channel="email"):Promise<any>{const row=(await context.pool.query("insert into notification_deliveries(id,template_key,channel,recipient,payload,status)values($1,$2,$3,$4,$5,'pending')returning *",[randomUUID(),template,channel,recipient,payload])).rows[0];return deliverNotification(context,row.id);}

async function kpis(context:AppContext,query:Record<string,any>):Promise<any>{const from=String(query.from??new Date(Date.now()-30*86400000).toISOString());const to=String(query.to??new Date().toISOString());const [sales,incidents,reasonsRows,merma,customizer,top,shipping]=await Promise.all([
  context.pool.query("select count(distinct order_id)::int paid_orders,count(*)::int sales_pings,coalesce(sum(quantity),0)::int items_sold,coalesce(sum(amount_mxn),0)::int revenue_mxn from sales_pings where occurred_at between $1 and $2",[from,to]),
  context.pool.query("select count(*)::int created_cases,count(*)filter(where status not in('resolved','closed'))::int open_cases from support_cases where created_at between $1 and $2",[from,to]),
  context.pool.query("select reason,count(*)::int count from support_cases where created_at between $1 and $2 group by reason order by count desc",[from,to]),
  context.pool.query("select count(*)::int events,coalesce(sum(quantity),0)::int units from work_order_failures where created_at between $1 and $2",[from,to]),
  context.pool.query("select count(*)filter(where event_type='customizer_started')::int started,count(*)filter(where event_type='customizer_added_to_cart')::int added_to_cart,count(*)filter(where event_type='customizer_abandoned')::int abandoned from analytics_events where occurred_at between $1 and $2",[from,to]),
  context.pool.query("select publication_id,publication_slug,sum(quantity)::int items_sold,sum(amount_mxn)::int revenue_mxn from sales_pings where occurred_at between $1 and $2 group by publication_id,publication_slug order by revenue_mxn desc limit 10",[from,to]),
  context.pool.query("select coalesce(provider,'unknown')provider,count(*)filter(where status='delivered')::int delivered_orders,count(*)filter(where status='failed')::int failed_orders,count(*)filter(where failed_attempts>0)::int incidents from shipments where created_at between $1 and $2 group by provider",[from,to])
]);const s=sales.rows[0]??{};const c=customizer.rows[0]??{};const abandonment=Number(c.started??0)>0?Number(c.abandoned??0)/Number(c.started)*100:0;return{from,to,sales:s,lead_times_minutes:{paid_to_designed_avg:null,designed_to_shipped_avg:null,paid_to_delivered_avg:null},incidents:{...(incidents.rows[0]??{}),by_reason:reasonsRows.rows},merma:merma.rows[0]??{events:0,units:0},customizer:{...c,abandonment_rate_pct:Number(abandonment.toFixed(2)),paid_items:Number(s.items_sold??0)},top_designs:top.rows,shipping_performance:shipping.rows.map(row=>({...row,avg_delivery_minutes:null})),margins:{gross_revenue_mxn:Number(s.revenue_mxn??0),estimated_cost_mxn:null,gross_margin_mxn:null,gross_margin_pct:null,coverage_orders:0}};}

export async function registerSupportAnalytics(app:FastifyInstance,context:AppContext):Promise<void>{
  app.get("/support/chat/reasons",async()=>({reasons}));
  const listCases=async(request:any,admin=false)=>{const query=asObject(request.query);const{limit,offset}=pagination(query);const values:any[]=[];const where:string[]=[];if(admin){for(const key of ["status","reason","linked_order_id","contact_email"])if(query[key]){values.push(query[key]);where.push(`${key}=$${values.length}`);}}else{const actor=await optionalActor(request);if(actor){values.push(actor.accountId);where.push(`account_id=$${values.length}`);}else{if(!query.guest_email||!query.guest_order_code)throw new HttpError(400,"Identidad de invitado requerida");values.push(String(query.guest_email).toLowerCase(),String(query.guest_order_code));where.push(`lower(guest_email)=$${values.length-1} and guest_order_code=$${values.length}`);}}values.push(limit,offset);const total=Number((await context.pool.query(`select count(*) from support_cases ${where.length?`where ${where.join(" and ")}`:""}`,values.slice(0,-2))).rows[0]?.count??0);const items=(await context.pool.query(`select * from support_cases ${where.length?`where ${where.join(" and ")}`:""} order by updated_at desc limit $${values.length-1} offset $${values.length}`,values)).rows;return{items,total,limit,offset};};
  app.get("/support/cases",async request=>listCases(request));
  app.post("/support/cases",async(request,reply)=>{const body=asObject(request.body);const actor=await optionalActor(request);const email=String(body.contact_email??body.guest_email??"").toLowerCase();if(!email)throw new HttpError(400,"contact_email requerido");let order:any=null;if(body.order_id)order=(await context.pool.query("select * from orders where id=$1",[body.order_id])).rows[0];else if(body.guest_order_code){const all=(await context.pool.query("select * from orders where lower(customer_email)=$1",[String(body.guest_email??email).toLowerCase()])).rows;order=all.find(row=>row.id.replaceAll("-","").slice(0,8).toUpperCase()===String(body.guest_order_code).replaceAll("-","").toUpperCase());}const id=randomUUID();await context.pool.query(`insert into support_cases(id,status,reason,priority,subject,customer_type,account_id,contact_email,contact_phone,guest_email,guest_order_code,linked_order_id,linked_order_code,is_order_related,metadata,created_by)
    values($1,'open',$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)`,[id,body.reason,body.priority??null,body.subject??null,actor?"account":"guest",actor?.accountId??null,email,body.contact_phone??null,actor?null:email,body.guest_order_code??null,order?.id??null,order?order.id.replaceAll("-","").slice(0,8).toUpperCase():body.guest_order_code??null,Boolean(body.is_about_order||order),body.metadata??null,actor?.accountId??email]);if(order)await context.pool.query("insert into support_case_order_links(id,case_id,order_id,order_code,link_method,created_by)values($1,$2,$3,$4,$5,$6)on conflict(case_id,order_id)do nothing",[randomUUID(),id,order.id,order.id.replaceAll("-","").slice(0,8).toUpperCase(),body.order_id?"id":"guest_code",actor?.accountId??email]);await addMessage(context,id,{message:body.message,attachments:body.attachments},{type:actor?"customer":"guest",accountId:actor?.accountId,label:email});await context.pool.query("insert into analytics_events(id,event_ref,event_type,support_case_id,status,occurred_at)values($1,$2,'support_case_created',$3,'open',now())on conflict(event_ref)do nothing",[randomUUID(),`support:${id}:created`,id]);reply.status(201);return caseDetail(context,id);});
  app.get<{Params:{case_id:string}}>("/support/cases/:case_id",async(request)=>{const detail=await caseDetail(context,request.params.case_id);await ensureCaseAccess(context,request,detail.case);return detail;});
  app.post<{Params:{case_id:string}}>("/support/cases/:case_id/messages",async(request)=>{const detail=await caseDetail(context,request.params.case_id);await ensureCaseAccess(context,request,detail.case);const actor=await optionalActor(request);return addMessage(context,request.params.case_id,asObject(request.body),{type:actor?"customer":"guest",accountId:actor?.accountId,label:detail.case.contact_email});});
  app.get("/admin/support/cases",async request=>listCases(request,true));app.get<{Params:{case_id:string}}>("/admin/support/cases/:case_id",async request=>caseDetail(context,request.params.case_id));
  app.patch<{Params:{case_id:string}}>("/admin/support/cases/:case_id/status",async(request)=>{const body=asObject(request.body);const row=(await context.pool.query("update support_cases set status=$2,closed_at=case when $2 in('resolved','closed')then now()else null end,updated_at=now()where id=$1 returning *",[request.params.case_id,body.status])).rows[0];if(!row)throw new HttpError(404,"Caso no encontrado");if(body.note)await addMessage(context,row.id,{message:body.note},{type:"agent",accountId:request.actor?.accountId,label:"Soporte"},true);if(body.notify_customer)await queueNotification(context,"support_case_update",row.contact_email,{subject:"Actualización de soporte",message:`Tu caso cambió a ${body.status}`,case_id:row.id});await audit(request,"support.status_updated","support_case",row.id,body);return caseDetail(context,row.id);});
  app.post<{Params:{case_id:string}}>("/admin/support/cases/:case_id/messages",async(request)=>{const result=await addMessage(context,request.params.case_id,asObject(request.body),{type:"agent",accountId:request.actor?.accountId,label:"Soporte"},Boolean(asObject(request.body).is_internal));await audit(request,"support.message_added","support_case",request.params.case_id);return result;});
  app.post<{Params:{case_id:string}}>("/admin/support/cases/:case_id/refunds",async(request)=>{const body=asObject(request.body);const support=(await context.pool.query("select * from support_cases where id=$1",[request.params.case_id])).rows[0];if(!support)throw new HttpError(404,"Caso no encontrado");const transaction=support.linked_order_id?(await context.pool.query("select pt.* from orders o join payment_transactions pt on pt.payment_attempt_id=o.payment_attempt_id where o.id=$1 order by pt.created_at desc limit 1",[support.linked_order_id])).rows[0]:null;const autoAllowed=Boolean(transaction&&body.mode==="auto");let recorded=false;if(transaction){const amount=Math.min(Number(body.amount_mxn??transaction.amount_mxn),Number(transaction.amount_mxn)-Number(transaction.refunded_amount_mxn));if(amount<=0)throw new HttpError(409,"No queda importe reembolsable");let providerRefundId:null|string=null;if(autoAllowed&&config.STRIPE_MODE==="live"&&transaction.provider_charge_id){const refund=await context.stripe.refunds.create({payment_intent:transaction.provider_charge_id,amount:amount*100,reason:"requested_by_customer"});providerRefundId=refund.id;}await context.pool.query("insert into refunds(id,payment_transaction_id,reason,amount_mxn,status,provider_refund_id)values($1,$2,$3,$4,$5,$6)",[randomUUID(),transaction.id,body.reason_code,amount,autoAllowed?"succeeded":"pending_manual",providerRefundId]);if(autoAllowed)await context.pool.query("update payment_transactions set refunded_amount_mxn=refunded_amount_mxn+$2,updated_at=now()where id=$1",[transaction.id,amount]);recorded=true;}await audit(request,"support.refund_recorded","support_case",support.id,body);return{case_id:support.id,mode:body.mode,reason_code:body.reason_code,auto_allowed:autoAllowed,recorded};});

  const notificationHandler=(template:string)=>async(request:any)=>{const body=asObject(request.body);const recipient=String(body.email??body.recipient??"");if(!recipient)throw new HttpError(400,"recipient requerido");return queueNotification(context,template,recipient,body,body.channel??"email");};
  app.post("/notifications/email/login-code",notificationHandler("login_code"));app.post("/notifications/email/login-magic-link",notificationHandler("login_magic_link"));app.post("/notifications/email/support-case-update",notificationHandler("support_case_update"));app.post("/notifications/email/order-confirmation",notificationHandler("order_confirmation"));app.post("/notifications/email/order-status-changed",notificationHandler("order_status_changed"));app.post("/notifications/internal/alerts",notificationHandler("internal_alert"));
  app.get("/admin/notifications/deliveries",async(request)=>{const q=asObject(request.query);const{limit,offset}=pagination(q);const values:any[]=[];const where:string[]=[];for(const key of ["status","template_key","channel","recipient"])if(q[key]){values.push(q[key]);where.push(`${key}=$${values.length}`);}values.push(limit,offset);const items=(await context.pool.query(`select * from notification_deliveries ${where.length?`where ${where.join(" and ")}`:""}order by created_at desc limit $${values.length-1} offset $${values.length}`,values)).rows;const total=Number((await context.pool.query(`select count(*) from notification_deliveries ${where.length?`where ${where.join(" and ")}`:""}`,values.slice(0,-2))).rows[0]?.count??0);return{items,total,limit,offset};});
  app.post<{Params:{delivery_id:string}}>("/admin/notifications/deliveries/:delivery_id/retry",async request=>deliverNotification(context,request.params.delivery_id));

  app.post("/analytics/customizer/events",async(request,reply)=>{const body=asObject(request.body);const id=randomUUID();await context.pool.query(`insert into analytics_events(id,event_ref,event_type,publication_id,item_type,garment_type,garment_model,color,size,grammage_g,fit,status,occurred_at,payload)
    values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,now(),$13)on conflict(event_ref)do nothing`,[id,body.event_ref??null,body.event_type??body.type??"customizer_event",body.publication_id??null,body.item_type??null,body.garment_type??null,body.garment_model??null,body.color??null,body.size??null,body.grammage_g??null,body.fit??null,body.status??null,body]);reply.status(202);return{accepted:true,event_id:id};});
  app.post("/internal/analytics/events",async(request,reply)=>{const body=asObject(request.body);const id=randomUUID();await context.pool.query("insert into analytics_events(id,event_ref,event_type,order_id,payment_attempt_id,support_case_id,work_order_id,status,amount_mxn,occurred_at,payload)values($1,$2,$3,$4,$5,$6,$7,$8,$9,coalesce($10,now()),$11)on conflict(event_ref)do nothing",[id,body.event_ref??null,body.event_type,body.order_id??null,body.payment_attempt_id??null,body.support_case_id??null,body.work_order_id??null,body.status??null,body.amount_mxn??null,body.occurred_at??null,body.payload??body]);reply.status(202);return{accepted:true,event_id:id};});
  app.post("/internal/analytics/sales/confirmed",async(request,reply)=>{const body=asObject(request.body);const id=randomUUID();await context.pool.query("insert into sales_pings(id,event_ref,order_id,payment_attempt_id,quantity,amount_mxn,shipping_method,occurred_at,payload)values($1,$2,$3,$4,$5,$6,$7,now(),$8)on conflict(event_ref)do nothing",[id,body.event_ref??`sale:${body.order_id}`,body.order_id,body.payment_attempt_id??null,body.quantity??1,body.amount_mxn??0,body.shipping_method??"unknown",body]);reply.status(202);return{accepted:true,id};});
  app.post("/internal/analytics/customizer/events",async(request,reply)=>{const body=asObject(request.body);const id=randomUUID();await context.pool.query("insert into analytics_events(id,event_ref,event_type,publication_id,status,occurred_at,payload)values($1,$2,$3,$4,$5,now(),$6)on conflict(event_ref)do nothing",[id,body.event_ref??null,body.event_type??"customizer_event",body.publication_id??null,body.status??null,body]);reply.status(202);return{accepted:true,event_id:id};});
  app.get("/analytics/map/pings",async(request)=>{const q=asObject(request.query);const{limit}=pagination(q);return(await context.pool.query("select * from sales_pings order by occurred_at desc limit $1",[limit])).rows;});
  app.get("/admin/analytics/kpis",async request=>kpis(context,asObject(request.query)));
  app.get("/ws/map",{websocket:true},socket=>{context.sockets.add(socket);socket.send(JSON.stringify({type:"connected",channel:"sales-map"}));socket.on("close",()=>context.sockets.delete(socket));});
  app.get("/ws",{websocket:true},socket=>{context.sockets.add(socket);socket.send(JSON.stringify({type:"connected",channel:"realtime"}));socket.on("close",()=>context.sockets.delete(socket));});
  app.post("/internal/broadcast",async(request)=>{const payload=JSON.stringify(asObject(request.body));let delivered=0;for(const socket of context.sockets)if(socket.readyState===1){socket.send(payload);delivered++;}return{delivered};});
}
